version: 0.2

phases:

  install:
    runtime-versions:
      golang: 1.22


    commands:

  pre_build:
    commands:

    # Fetch all dependencies
    - go get ./...

    # Check for common Go application problems with 'go vet'
    - go vet .
    
    # Display sam version
    - sam --version

  build:
    commands:

    # Build go application
    - go build -o main

    - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

  post_build:
    commands:

artifacts:
  files:
  - template-export.yml
