AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
    Description: Project Name
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  AWSAccountNumber:
    Type: String
    Description: Deployment AWS Account Number

Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Type: AllAtOnce
      Role: !Ref CodeDeployRole

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref ProjectName
      Description: Lambda pipeline test function
      Handler: main
      Runtime: go1.x
      MemorySize: 512
      Timeout: 60
      Role: !GetAtt LambdaPipelineTestExecutionRole.Arn
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Sub arn:aws:sns:us-east-1:${AWSAccountNumber}:LambdaPipelineTest-topic
  LambdaPipelineTestExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-LambdaExecutionRole
      Description: Lambda execution role
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
